EjercicioTalper/Controllers/CaptureController.cs
using EjercicioTalper.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EjercicioTalper.Controllers
{
    public class CaptureController : Controller
    {
        // GET: Capture
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Models.ViewModels.ProspectoViewModel model, HttpPostedFileBase[] file) 
        {
            DbTransaction transaction;
            try
            {
                model.Documentos = getDocuments(file);
                using (Models.EjercicioTalperEntities db = new Models.EjercicioTalperEntities())
                {
                    db.Database.Connection.Open();
                    transaction = db.Database.Connection.BeginTransaction();
                    db.Database.UseTransaction(transaction);
                    try
                    {
                        Models.Prospectos prospecto = new Models.Prospectos();
                        prospecto.Nombre = model.Nombre.ToUpper();
                        prospecto.ApellidoPaterno = model.ApellidoPaterno.ToUpper();
                        prospecto.ApellidoMaterno = model.ApellidoMaterno.ToUpper();
                        prospecto.Calle = model.Calle.ToUpper();
                        prospecto.Numero = model.Numero.ToUpper();
                        prospecto.Colonia = model.Colonia.ToUpper();
                        prospecto.CodigoPostal = model.CodigoPostal;
                        prospecto.Telefono = model.Telefono.ToUpper();
                        prospecto.RFC = model.RFC.ToUpper();
                        prospecto.Estatus = "REVISIÓN";
                        db.Prospectos.Add(prospecto);
                        db.SaveChanges();
                        foreach (var document in model.Documentos)
                        {
                            Models.Documentos documento = new Models.Documentos();
                            documento.FKProspecto = prospecto.PKProspecto;
                            documento.Nombre = document.Nombre;
                            documento.Archivo = document.Archivo;
                            db.Documentos.Add(documento);
                            db.SaveChanges();
                        }
                        transaction.Commit();
                        db.Database.Connection.Close();
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        db.Database.Connection.Close();
                        ViewBag.ErrorMessage = "Error al Insertar " + ex.Message;
                        Console.WriteLine("Error en: " + ex);
                    }
                   
                }
                ViewBag.Message = "Registro Exitoso";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error al Insertar " + ex.Message ;
                Console.WriteLine("Error en: "+ex);
                return View();
            }
        }

        private List<DocumentoViewModel> getDocuments(HttpPostedFileBase[] files)
        {
            List<DocumentoViewModel> documents = new List<DocumentoViewModel>();
            
            foreach (var file in files)
            {
                DocumentoViewModel document = new DocumentoViewModel();
              if(file!=null)
                if (file.ContentLength > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);                       
                        document.Nombre = Path.GetFileName(file.FileName);
                        document.Archivo = ms.ToArray();
                        documents.Add(document);
                    }
                }
                }
            return  documents;
        }

    }
}

EjercicioTalper/Views/Capture/Add.cshtml
@model EjercicioTalper.Models.ViewModels.ProspectoViewModel
@{
    ViewBag.Title = "Capturar Prospecto";
}
<link rel="stylesheet" href="~/Scripts/CSS/materialize.min.css">
<link rel="stylesheet" href="~/Scripts/CSS/materialize.css">
<div class="alert-success">@ViewBag.Message</div>
<div class="alert-danger">@ViewBag.ErrorMessage</div>
<h2 style="text-decoration:dashed; text-align:center;">@ViewBag.Title</h2>
<div>
    @using (Html.BeginForm("Add", "Capture", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <form id="applyForm">
            <div class="row">
                <div class="col s12">
                    <div class="input-field col s12 m4">
                        <input id="txtNombre" type="text" name="Nombre" class="@(ViewData.ModelState.ContainsKey("Nombre") && ViewData.ModelState["Nombre"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="txtNombre">Nombre(s) *</label>
                    </div>
                    <div class="input-field col s12 m4">
                        <input id="txtApellidoPaterno" type="text" name="ApellidoPaterno" class="@(ViewData.ModelState.ContainsKey("ApellidoPaterno") && ViewData.ModelState["ApellidoPaterno"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="txtApellidoPaterno">Apellido Paterno *</label>
                    </div>
                    <div class="input-field col s12 m4">
                        <input id="txtApellidoMaterno" type="text" name="ApellidoMaterno" class="@(ViewData.ModelState.ContainsKey("ApellidoMaterno") && ViewData.ModelState["ApellidoMaterno"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="ApellidoMaterno">Apellido Materno *</label>
                    </div>
                    <br />
                    <div class="input-field col s12 m4">
                        <input id="txtCalle" type="text" name="Calle" class="@(ViewData.ModelState.ContainsKey("Calle") && ViewData.ModelState["Calle"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="txtCalle">Calle *</label>
                    </div>
                    <div class="input-field col s12 m4">
                        <input id="txtNumero" type="text" name="Numero" class="@(ViewData.ModelState.ContainsKey("Numero") && ViewData.ModelState["Numero"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="txtNumero">Número *</label>
                    </div>
                    <div class="input-field col s12 m4">
                        <input id="txtColonia" type="text" name="Colonia" class="@(ViewData.ModelState.ContainsKey("Colonia") && ViewData.ModelState["Colonia"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="txtColonia">Colonia *</label>
                    </div>
                    <br />
                    <div class="input-field col s12 m4">
                        <input id="txtCodigoPostal" type="number" name="CodigoPostal" class="@(ViewData.ModelState.ContainsKey("CodigoPostal") && ViewData.ModelState["CodigoPostal"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="txtCodigoPostal">Código Postal *</label>
                    </div>
                    <div class="input-field col s12 m4">
                        <input id="txtTelefono" type="text" name="Telefono" class="@(ViewData.ModelState.ContainsKey("Telefono") && ViewData.ModelState["Telefono"].Errors.Any() ? "input-validation-error" : string.Empty )" required />
                        <label for="txtTelefono">Teléfono *</label>
                    </div>
                    <div class="input-field col s12 m4">
                        <input id="txtRFC" type="text" name="RFC" class="@(ViewData.ModelState.ContainsKey("RFC") && ViewData.ModelState["RFC"].Errors.Any() ? "input-validation-error" : string.Empty )" required maxlength="13" />
                        <label for="txtRFC">RFC *</label>
                    </div>
                    <br />
                    <div id="goals-documents">
                        <label>Documento(s) *</label>
                        <input type="file" name="file" required />
                        <br />
                    </div>
                    <button class="btn-primary" title="Agregar Documento" id="add-Documento" type="button" onclick="addDocument()">+</button>
                    <br />
                    <div class="form-group" style="text-align:center">
                        <input contextmenu="Guardar" type="submit" class="btn btn-success" style="width: 150px;" title="Guardar" />
                    </div>
                </div>
            </div>
        </form>
    }

    <template id="templete-documentos">
        <input type="file" name="file" required />
        <br />
    </template>
    <script src="~/Scripts/materialize.min.js"></script>
    <script>

        function addDocument(args, evt) {
            var result = confirm("¿Esta Seguro de agregar otro documento?");
            if (result == true) {
                var documento = $('#templete-documentos').html();
                $('#goals-documents').append(documento);
            } else {
                return;
            }
            window.onbeforeunload = areYouSure();
            var areYouReallySure = false;
            function areYouSure() {
                debugger;
                if (allowPrompt) {
                    if (!areYouReallySure && true) {
                        areYouReallySure = true;
                        var confMessage = "Si sale perdera toda la imformación no guradada ¿Esta seguro de salir? ";
                        return confMessage;
                    }
                } else {
                    allowPrompt = true;
                }
            }

            var allowPrompt = true;
            window.onbeforeunload = areYouSure;
        }
    </script>
</div>